Module3 task1
htmlacademy-react/838151-what-to-watch-6 pull request #5
Opened 2021-02-10 15:44 UTC by Kiriuha-lucky

2021-02-11 10:12 UTC, iseekyouu commented on src/components/app/app.js
> +        <Route exact path="/films/:id?/review" component={AddReview} />
почему ты тут и в компоненте ниже параметр id сделал не обязательным?

2021-02-11 10:16 UTC, iseekyouu commented on src/components/add-review/add-review.js
> +import FILMS from '../../mocks/films';
по заданию у тебя список фильмов должен через пропсы приходить

Передайте страницам «MyList», «Player», «Add review» через props набор данных (объектов) из моков. Вместо статичной вёрстки, на страницах должна отрисовываться информация из моков. Не забудьте добавить с помощью пакета PropTypes валидацию props.

2021-02-11 10:20 UTC, iseekyouu commented on src/components/film/film.js
> +            <FilmsList films={FILMS.filter((movie)=>movie.genre === film.genre).slice(0, 4)} />
не понял для чего ты тут фильтруешь и берешь первые 4?

2021-02-11 10:23 UTC, iseekyouu commented on src/components/player/player.js
> +        <button type="button" className="player__exit" onClick={goBack}>Exit</button>
не нашел в задании, сделать history back, напиши, что тут надо было сделать

2021-02-11 10:25 UTC, iseekyouu commented on src/index.js
> +    <App movie={Movie} films={FILMS} />,
movie уже наверно не нужен?

2021-02-11 10:31 UTC, iseekyouu commented on src/components/app/app.js
> +        <Route exact path="/films/:id?" component={Film} />
судя по этому роуту компонент карточки фильма у тебя Film, а что тогда за компонент MovieCard, который используется в Films?

2021-02-11 10:33 UTC, iseekyouu requested changes
вопросы в комментариях?

2021-02-11 10:36 UTC, iseekyouu commented on src/components/films-list.js
> +    <MovieCard key={id} id={id} name={name} posterImage={posterImage} onMouseEnter={() => setActiveFilm(activeFilm)} />);
тут в сет актив надо передавать ид фильма

2021-02-11 10:38 UTC, Kiriuha-lucky commented on src/components/app/app.js
> +        <Route exact path="/films/:id?/review" component={AddReview} />
это я временно на прошлом шаге поставил чтобы не падала ошибка при переходе на AddReview сейчас их уберу потому что уже id передается всегда

2021-02-11 10:44 UTC, Kiriuha-lucky commented on src/components/add-review/add-review.js
> +import FILMS from '../../mocks/films';
да это как раз я тебя спрашивал и так и не понял как сделать:
- если я делаю вот так "<Route exact path="/films/:id?/review" component={AddReview} />" то могу получить id из заголовка, но не могу пропихнуть туда films как props;
- если я делаю так" <Route exact path="/films/:id?/review">
      <AddReview films={films} />
  </Route>", то передаю через props films, но не могу получить id фильма

и я так в итоге и не врубился как и films в props пропихнуть и id можно было получать из заголовка

2021-02-11 10:45 UTC, Kiriuha-lucky commented on src/components/film/film.js
> +            <FilmsList films={FILMS.filter((movie)=>movie.genre === film.genre).slice(0, 4)} />
в шаблоне примера было 4 элемента и я тоже решил также сделать чтобы было 4

2021-02-11 10:47 UTC, Kiriuha-lucky commented on src/components/player/player.js
> +        <button type="button" className="player__exit" onClick={goBack}>Exit</button>
я думал это вот в этой части задания надо было сделать "Используя компонент Link из пакета react-router-dom и возможности пропса history свяжите страницы приложения. Например, клик по заголовку карточки с фильмом перенаправляет пользователя на страницу «Film» с подробным описанием фильма.", потому что link для перехода в player я добавляю, а что повесить на кнопку закрыть player,чтобы вернуться назад я не знал

2021-02-11 10:51 UTC, Kiriuha-lucky commented on src/components/app/app.js
> +        <Route exact path="/films/:id?" component={Film} />
MovieCard (карточка фильма) это карточка одного фильма, которая попадает в FilmList (и получается список фильмов), а уже FilmsList вставляется туда куда надо отрисовать список фильмов, это я сделал по "Создайте новый компонент «Список фильмов. Компонент должен отрисовывать карточки фильмов с помощью компонента «Карточка фильма. Все необходимые данные компонент принимает через props. Не забудьте описать правила валидации для props. В стейте компонента должна быть активная карточка с фильмом (объект с данными фильма или лишь уникальный идентификатор фильма). Под активной карточкой фильма подразумевается карточка, на которую пользователь навёл курсор."

2021-02-11 10:55 UTC, Kiriuha-lucky commented on src/index.js
> +    <App movie={Movie} films={FILMS} />,
ну movie это у меня промо фильм в заголовке страницы, по заданию он будет получаться отдельным запросом "GET /films/promo
Получение промо-фильма.

Коды ответов:
200 ОК
Пример:

Request:
URL: GET /films/promo
Response:
Status: 200 OK
Body: структуры Film", поэтому я решил его оставить отдельным объектом пока что

2021-02-11 10:57 UTC, Kiriuha-lucky commented on src/components/films-list.js
> +    <MovieCard key={id} id={id} name={name} posterImage={posterImage} onMouseEnter={() => setActiveFilm(activeFilm)} />);
да здесь у меня было вот так "onMouseEnter={() => setActiveFilm(activeFilm = id)}", но eslint ругается что activeFilm ни где не используется поэтому я часть убрал

2021-02-11 12:03 UTC, iseekyouu commented on src/components/add-review/add-review.js
> +import FILMS from '../../mocks/films';
посмотри доку https://reactrouter.com/web/api/Route/route-render-methods
попробуй использовать функцию render или передать чилдреном с пропсом

2021-02-11 12:04 UTC, iseekyouu commented on src/components/film/film.js
> +            <FilmsList films={FILMS.filter((movie)=>movie.genre === film.genre).slice(0, 4)} />
ты не ответил про фильтр, в любом случае в задании нет такого требования, пока это выглядит лишним, оставь тут как хочешь

2021-02-11 12:09 UTC, iseekyouu commented on src/components/player/player.js
> +        <button type="button" className="player__exit" onClick={goBack}>Exit</button>
в задании ничего не написано про то что должно происходить при закрытии плеера, ладно давай так пока оставим

2021-02-11 12:14 UTC, iseekyouu commented on src/components/films-list.js
> +    <MovieCard key={id} id={id} name={name} posterImage={posterImage} onMouseEnter={() => setActiveFilm(activeFilm)} />);
это не повод писать код с ошибками, флаг активности явно будет использоваться в карточке  фильма, передай лучше его туда пропсом, чтобы линт не ругался

2021-02-11 12:16 UTC, iseekyouu commented on src/components/app/app.js
> +        <Route exact path="/films/:id?" component={Film} />
хм, смущает что в компоненте FIlm в верстке movie_card, ну ладно давай пока оставим так, но плохо, что у тебя компонент называется FIlm а карточка фильма MovieCard, как будто у тебя есть 2 разных сущности film и movie, лучше сделать ренейм. Film -> Movie | MoviePage

2021-02-11 12:18 UTC, iseekyouu commented
очень смущает, что в коде есть много штук, котрых нет в задании - это сильно сбивает, так как не понятно баг это или фича

2021-02-12 09:57 UTC, Kiriuha-lucky commented on src/components/film/film.js
> +            <FilmsList films={FILMS.filter((movie)=>movie.genre === film.genre).slice(0, 4)} />
а да ну это я пока просто добавил чтобы он из всех фильмов выбирал те которые подходят к текущему фильму по жанру

2021-02-12 09:58 UTC, Kiriuha-lucky commented on src/components/add-review/add-review.js
> +import FILMS from '../../mocks/films';
исправил, заменил на render c props

2021-02-12 11:14 UTC, Kiriuha-lucky commented on src/components/app/app.js
> +        <Route exact path="/films/:id?" component={Film} />
"Приложение состоит из нескольких страниц: Main (/), Sign In (/login), MyList (/mylist), Film (/films/:id), Add review (/films/:id/review), Player (/player/:id)." должна быть страница Film сделал из MovieCard -> FilmCard

2021-02-12 12:26 UTC, iseekyouu commented on src/components/app/app.js
> +        )}/>
тут скорее всего  id тоже не должен быть не обязательным параметром.
prop -> props
если тебе не нужны эти пропсы в компоненте, то пробрасывать их не обязательно

2021-02-12 12:33 UTC, iseekyouu commented on src/components/films-list.js
> +    return setActiveFilm(activeFilm = id);
тут ошибка.
в аргументах не нужно делать каких-либо действий это плохая практика.
И я не понял, что ты хотел сделать этим действием, тут надо сделать вот так
`setActiveFIlm(id)`

2021-02-12 12:34 UTC, Kiriuha-lucky commented on src/components/app/app.js
> +        )}/>
ну да нужны я же из них id фильма вытаскиваю

2021-02-12 12:35 UTC, iseekyouu commented on src/components/films-list.js
> +  let [activeFilm, setActiveFilm] = React.useState(0);
let -> const

2021-02-12 12:42 UTC, iseekyouu commented
хорошие названия коммитов!

2021-02-13 20:12 UTC, Kiriuha-lucky commented on src/components/films-list.js
> +    return setActiveFilm(activeFilm = id);
поменял на setActiveFilm(id) и убрал return

2021-02-13 20:12 UTC, Kiriuha-lucky commented on src/components/films-list.js
> +  let [activeFilm, setActiveFilm] = React.useState(0);
поменял let to const

2021-02-15 15:12 UTC, iseekyouu approved these changes

2021-02-15 15:12 UTC, merged